Inventory.Web/Controllers/ElementController.cs
using Inventory.Web.Models.Dto;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace Inventory.Web.Controllers
{
    public class ElementController : Controller
    {
        readonly Uri baseAddress = new("https://localhost:44336/api");
        private readonly HttpClient _client;
        public ElementController()
        {
            _client = new HttpClient
            {
                BaseAddress = baseAddress
            };
        }
        
        public IActionResult ElementIndex()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAllElements()
        {
            try
            {
                List<ElementDto> list = new();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Element/Get").Result;
                if (response.IsSuccessStatusCode && response != null)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    list = JsonConvert.DeserializeObject<List<ElementDto>>(data);
                }
                return Json(list.ToArray());
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult CreateElement(ElementDto obj)
        {
            try
            {
                string data = JsonConvert.SerializeObject(obj);
                StringContent content = new(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Element/Create", content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return Json("Element created successfully");
                }
                else
                {
                    return Json("Element not created");
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }       
        }

        [HttpPost]
        public IActionResult UpdateElement(ElementDto obj)
        {
            try
            {
                string data = JsonConvert.SerializeObject(obj);
                StringContent content = new(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + "/Element/Update/" + obj.Id, content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return Json("Element updated successfully");
                }
                else
                {
                    return Json("Element not updated");
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult DeleteElement(int id)
        {
            try
            {
                string data = JsonConvert.SerializeObject(id);
                StringContent content = new(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Element/Delete/" + id, content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return Json("Element deleted successfully");
                }
                else
                {
                    return Json("Element not deleted");
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }
    }
}

Inventory.Web/Controllers/RackController.cs
using AutoMapper;
using Inventory.Web.Models.Dto;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;
using System.Text;

namespace Inventory.Web.Controllers
{
    public class RackController : Controller
    {
        readonly Uri baseAddress = new("https://localhost:44336/api");
        private readonly HttpClient _client;
        private readonly IMapper _mapper;

        public RackController(IMapper mapper)
        {
            _client = new HttpClient
            {
                BaseAddress = baseAddress
            };
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult RackIndex()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAllRacks()
        {
            try
            {
                List<RackDto> list = new();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Rack/Get").Result;
                if (response.IsSuccessStatusCode && response != null)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    list = JsonConvert.DeserializeObject<List<RackDto>>(data);
                }
                return Json(list.ToArray());
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult CreateRack(RackDto obj)
        {
            try
            {
                string data = JsonConvert.SerializeObject(obj);
                StringContent content = new(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Rack/Create", content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return Json("Rack created successfully");
                }
                else
                {
                    return Json("Rack not created");
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult UpdateRack(RackDto obj)
        {
            try
            {
                string data = JsonConvert.SerializeObject(obj);
                StringContent content = new(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + "/Rack/Update/" + obj.Id, content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return Json("Rack updated successfully");
                }
                else
                {
                    return Json("Rack not updated");
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult DeleteRack(int id)
        {
            try
            {
                string data = JsonConvert.SerializeObject(id);
                StringContent content = new(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Rack/Delete/" + id, content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return Json("Rack deleted successfully");
                }
                else
                {
                    return Json("Rack not deleted");
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
            
        }
    }
}

Inventory.Web/Controllers/ReportController.cs
using Inventory.Domain.Entities;
using Inventory.Persistence.DbContexts;
using Inventory.Web.Models.Dto;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;
using System.Reflection.Metadata;
using System.Text;

namespace Inventory.Web.Controllers
{
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ReportController(ApplicationDbContext db)
        {
            _db= db;
        }
        public string GetReport()
        {
            StringBuilder sb = new StringBuilder();
            var elementList = _db.Elements
                .Select(s => new
                {
                    StoreName = s.Rack.Store.Name,
                    Country = s.Rack.Store.Country,
                    RackName = s.Rack.Name,
                    QuantityOfRacks = s.Rack.QuantityOfRacks,
                    ElementName = s.Name,
                    Width = s.Width,
                    Height = s.Height
                }).ToList();
            List<StoreDto> storeList = new();
            List<RackDto> rackList = new();
            storeList = _db.Stores
                .Select(s => new StoreDto
                {
                    Name = s.Name,
                    Country = s.Country
                })
                .Distinct()
                .ToList();
            rackList = _db.Racks
                   .Select(s => new RackDto
                   {
                       Name = s.Name,
                       QuantityOfRacks = s.QuantityOfRacks,
                       StoreName = s.Store.Name
                   })
                   .Distinct()
                   .ToList();
            sb.Append("<Stores>");
            foreach (var store in storeList)
            {
                // Store opening tag
                sb.Append("\r\n\t<Store Name=\""+ store.Name+ "\" Country=\""+store.Country+"\">");
                // Racks opening tag
                sb.Append("\r\n\t\t<Racks>");
                var filteredrackList = rackList.Where(w => w.StoreName == store.Name);
                foreach (var rack in filteredrackList)
                {
                    var totalElement = elementList.Where(w => w.RackName == rack.Name).Count();
                    //Rack opening tag
                    sb.Append("\r\n\t\t\t<Rack Name=\""+ rack.Name+ "\" QuantityOfRacks=\""+rack.QuantityOfRacks+"\" TotalElements=\""+ totalElement + "\">");
                    //Elements opening tag
                    sb.Append("\r\n\t\t\t\t<Elements>");
                    var filteredElementList = elementList.Where(w => w.RackName == rack.Name);
                    foreach (var element in filteredElementList)
                    {
                        // Element opening tag and closing tag
                        sb.Append("\r\n\t\t\t\t\t<Element Element=\""+ element.ElementName+ "\" Width=\""+element.Width+"\" Height=\""+element.Height+ "\" />");
                    }
                    //Elements closing tag
                    sb.Append("\r\n\t\t\t\t</Elements>");
                    //Rack (not plural) closing tag
                    sb.Append("\r\n\t\t\t</Rack>");
                }
                // Racks closing tag
                sb.Append("\r\n\t\t</Racks>");
                // Store closing tag
                sb.Append("\r\n\t</Store>");
            }
            sb.Append("\r\n</Stores>");
            return sb.ToString();

        }
    }
}

Inventory.Web/Controllers/StoreController.cs
using Inventory.Web.Models.Dto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Text;

namespace Inventory.Web.Controllers
{
    public class StoreController : Controller
    {
        readonly Uri baseAddress = new("https://localhost:44336/api");
        private readonly HttpClient _client;
        public StoreController()
        {
            _client = new HttpClient
            {
                BaseAddress = baseAddress
            };
        }
        public IActionResult StoreIndex()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAllStores()
        {
            try
            {
                List<StoreDto> list = new();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Store/Get").Result;
                if (response.IsSuccessStatusCode && response != null)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    list = JsonConvert.DeserializeObject<List<StoreDto>>(data);                    
                }
                return Json(list.ToArray());
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult CreateStore(StoreDto obj)
        {
            try
            {
                string data = JsonConvert.SerializeObject(obj);
                StringContent content = new(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Store/Create", content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return Json("Store created successfully");
                }
                else
                {
                    return Json("Store not created");
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult UpdateStore(StoreDto obj)
        {
            try
            {
                string data = JsonConvert.SerializeObject(obj);
                StringContent content = new(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + "/Store/Update/" + obj.Id, content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return Json("Store updated successfully");
                }
                else
                {
                    return Json("Store not updated");
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult DeleteStore(int id)
        {
            try
            {
                string data = JsonConvert.SerializeObject(id);
                StringContent content = new(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Store/Delete/" + id, content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return Json("Store deleted successfully");
                }
                else
                {
                    return Json("Store not deleted");
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }
    }
}

Inventory.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventory.Web</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <!-- bootstrap-table.min.css -->
    <link href="~/css/bootstrap-table.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/Inventory.Web.styles.css" asp-append-version="true" />
    <!-- sweetalert2 -->
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.css">
    <!-- Toastr -->
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css">

    <!--Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://unpkg.com/ionicons@4.5.5/dist/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <style>
        .nav-item:hover {
            background-color: #9c59c9;
        }

        .active {
            background-color: blueviolet;
        }

        .nav-item {
            padding-top: 8px;
            padding-bottom: 8px;
            padding-left: 8px;
            padding-right: 8px;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3 py-0">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Inventory.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="ms-5 ps-5 navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Store" asp-action="StoreIndex">Store</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Rack" asp-action="RackIndex">Rack</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Element" asp-action="ElementIndex">Element</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Report" asp-action="GetReport">Report</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2023 - Inventory.Web
        </div>
    </footer>

    <!-- bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- bootstrap-table -->
    <script src="~/js/bootstrap-table.min.js" type="text/javascript"></script>
    @*exporting cdns*@
    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/extensions/export/bootstrap-table-export.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.10.21/tableExport.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.10.21/libs/jsPDF/jspdf.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.10.21/libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/extensions/export/bootstrap-table-export.min.js"></script>

    <!-- sweetalert2 -->
    <script src="~/lib/sweetalert2/sweetalert2.js"></script>
    <!-- Toastr -->
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)



</body>
</html>